import {
  Member,
  HomeGroup,
  Department,
  FellowshipEvent,
  AttendanceRecord,
  FollowUpRecord,
  IncomeRecord,
  ExpenseRecord,
  Budget,
  FinancialProject,
  AuditLog,
  CommunicationMessage,
} from './types';

export const INITIAL_HOMES: HomeGroup[] = [
  {
    id: 'home-sinai',
    name: 'Home Sinai',
    zone: 'Kansanga - KIU Main Campus Zone',
    leaderId: 'MAN-2026-000004',
    leaderName: 'Kato Emmanuel',
    leaderPhone: '+256 772 345678',
    assistantLeaderId: 'MAN-2026-000008',
    assistantLeaderName: 'Nakato Grace',
    meetingDay: 'Wednesdays at 6:30 PM',
    location: 'KIU Main Gate / Kalungi Plaza Lounge, Kansanga',
    description: 'Serving KIU campus students and hostel residents along Ggaba Road.',
    targetCount: 40,
  },
  {
    id: 'home-zion',
    name: 'Home Zion',
    zone: 'Kansanga Hostels & Heritage Zone',
    leaderId: 'MAN-2026-000002',
    leaderName: 'Mugisha Brian',
    leaderPhone: '+256 701 892341',
    assistantLeaderId: 'MAN-2026-000010',
    assistantLeaderName: 'Ahebwa Faith',
    meetingDay: 'Wednesdays at 7:00 PM',
    location: 'Prestige Hostel Common Quad, Kansanga',
    description: 'Active cell for KIU hostel residents around Heritage Park & Wonder World area.',
    targetCount: 50,
  },
  {
    id: 'home-bethel',
    name: 'Home Bethel',
    zone: 'Kabalagala & Bukasa Zone',
    leaderId: 'MAN-2026-000005',
    leaderName: 'Ssemwogerere David',
    leaderPhone: '+256 784 551234',
    meetingDay: 'Thursdays at 5:30 PM',
    location: 'Tirupati Heights Lounge, Kabalagala',
    description: 'Gathering for students and professionals along Muyenga junction and Bukasa corridor.',
    targetCount: 35,
  },
  {
    id: 'home-ebenezer',
    name: 'Home Ebenezer',
    zone: 'Ggaba & Bunga Lake Zone',
    leaderId: 'MAN-2026-000007',
    leaderName: 'Atuhaire Brenda',
    leaderPhone: '+256 753 112233',
    meetingDay: 'Tuesdays at 6:30 PM',
    location: 'Ggaba Trading Center / Lake Breeze Garden',
    description: 'Community for KIU commuters and fellowship members residing in Ggaba and Bunga.',
    targetCount: 30,
  },
  {
    id: 'home-shiloh',
    name: 'Home Shiloh',
    zone: 'Nsambya & Kibuli Zone',
    leaderId: 'MAN-2026-000012',
    leaderName: 'Ocen Timothy',
    leaderPhone: '+256 779 667788',
    meetingDay: 'Wednesdays at 6:00 PM',
    location: 'Nsambya Community Center, Gogonya',
    description: 'Hub serving students and families in Nsambya, Kibuli, and Hanlon Road.',
    targetCount: 45,
  },
  {
    id: 'home-moriah',
    name: 'Home Moriah',
    zone: 'Makindye & Luwafu Zone',
    leaderId: 'MAN-2026-000015',
    leaderName: 'Namubiru Joy',
    leaderPhone: '+256 702 449911',
    meetingDay: 'Thursdays at 6:00 PM',
    location: 'Makindye Hill Fellowship House, Lukuli Nanganda',
    description: 'Home fellowship catering to residents of Makindye Hill, Luwafu, and Kizungu.',
    targetCount: 40,
  },
];

export const INITIAL_DEPARTMENTS: Department[] = [
  {
    id: 'dept-choir',
    name: 'Choir & Worship Ministry',
    code: 'CHOIR',
    leaderId: 'MAN-2026-000003',
    leaderName: 'Nabatanzi Rachel',
    leaderPhone: '+256 774 991122',
    description: 'Leads the fellowship in deep, spirit-filled praise, worship, and vocal ministry.',
    meetingSchedule: 'Saturdays 3:00 PM (Rehearsal) & Thursdays 4:30 PM (Sound Check)',
  },
  {
    id: 'dept-media',
    name: 'Media, Sound & Production',
    code: 'MEDIA',
    leaderId: 'MAN-2026-000001',
    leaderName: 'Kigozi Joshua',
    leaderPhone: '+256 703 118844',
    description: 'Responsible for live streaming, audio engineering, photography, and digital content.',
    meetingSchedule: 'Fridays 5:00 PM & Fellowship Pre-Service Setup',
  },
  {
    id: 'dept-protocol',
    name: 'Protocol & Ushers',
    code: 'PROTOCOL',
    leaderId: 'MAN-2026-000009',
    leaderName: 'Kembabazi Sandra',
    leaderPhone: '+256 781 445566',
    description: 'Welcoming attendees, seat coordination, guest reception, and offering management.',
    meetingSchedule: 'Thursdays 4:30 PM Briefing & Monthly Training',
  },
  {
    id: 'dept-prayer',
    name: 'Intercession & Spiritual Warfare',
    code: 'PRAYER',
    leaderId: 'MAN-2026-000002',
    leaderName: 'Mugisha Brian',
    leaderPhone: '+256 701 892341',
    description: 'Midnight prayer watches, pre-service prayer cover, and weekly intercessory chain.',
    meetingSchedule: 'Tuesdays 9:00 PM Online Watch & Thursdays 4:00 PM Altar',
  },
  {
    id: 'dept-outreach',
    name: 'Outreach & KIU Campus Evangelism',
    code: 'OUTREACH',
    leaderId: 'MAN-2026-000006',
    leaderName: 'Okello Paul',
    leaderPhone: '+256 756 778899',
    description: 'Hostel evangelism, KIU Kansanga missions, hospital visits, and freshers welcome.',
    meetingSchedule: 'Saturdays 10:00 AM Mission Deployments',
  },
  {
    id: 'dept-coordination',
    name: 'First-Timers Pastoral Care',
    code: 'CARE',
    leaderId: 'MAN-2026-000014',
    leaderName: 'Akello Mercy',
    leaderPhone: '+256 704 332211',
    description: 'Welcomes first-timers, tracks personal integration, and coordinates home placement.',
    meetingSchedule: 'Fridays 4:00 PM Follow-Up Review',
  },
];

export const INITIAL_MEMBERS: Member[] = [
  {
    id: 'MAN-2026-000001',
    fullName: 'Kigozi Joshua',
    preferredName: 'Josh',
    gender: 'Male',
    phone: '+256 703 118844',
    altPhone: '+256 772 118844',
    email: 'joshua.kigozi@manifestfellowship.org',
    dateOfBirth: '2001-04-14',
    studentInfo: {
      isStudent: true,
      registrationNumber: '2021-01-04231',
      course: 'BSc Software Engineering',
      faculty: 'School of Computing & IT',
      yearOfStudy: 4,
      campus: 'KIU - Main Campus (Kansanga)',
      expectedGraduationYear: 2026,
    },
    status: 'Active',
    isFirstTimer: false,
    dateOfFirstAttendance: '2023-08-15',
    registrationDate: '2023-08-18',
    howFoundManifest: 'Friend/Member',
    homeId: 'home-sinai',
    departmentIds: ['dept-media'],
    notes: 'Technical lead and media coordinator at KIU Kansanga.',
  },
  {
    id: 'MAN-2026-000002',
    fullName: 'Mugisha Brian',
    preferredName: 'Brian',
    gender: 'Male',
    phone: '+256 701 892341',
    email: 'brian.mugisha@gmail.com',
    dateOfBirth: '2002-11-03',
    studentInfo: {
      isStudent: true,
      registrationNumber: '2022-08-01994',
      course: 'Bachelor of Laws (LLB)',
      faculty: 'School of Law',
      yearOfStudy: 3,
      campus: 'KIU - School of Law (Kansanga)',
      expectedGraduationYear: 2027,
    },
    status: 'Active',
    isFirstTimer: false,
    dateOfFirstAttendance: '2023-09-02',
    registrationDate: '2023-09-05',
    howFoundManifest: 'Campus Outreach',
    homeId: 'home-zion',
    departmentIds: ['dept-prayer'],
    notes: 'Home Zion leader in Kansanga hostels.',
  },
  {
    id: 'MAN-2026-000003',
    fullName: 'Nabatanzi Rachel',
    preferredName: 'Rachel',
    gender: 'Female',
    phone: '+256 774 991122',
    email: 'rachel.nabatanzi@outlook.com',
    dateOfBirth: '2003-01-22',
    studentInfo: {
      isStudent: true,
      registrationNumber: '2022-05-08812',
      course: 'Bachelor of Business Administration (BBA)',
      faculty: 'School of Business & Management',
      yearOfStudy: 3,
      campus: 'KIU - Main Campus (Kansanga)',
      expectedGraduationYear: 2026,
    },
    status: 'Active',
    isFirstTimer: false,
    dateOfFirstAttendance: '2023-10-10',
    registrationDate: '2023-10-12',
    howFoundManifest: 'Friend/Member',
    homeId: 'home-moriah',
    departmentIds: ['dept-choir'],
    notes: 'Choir Director and Praise team vocalist residing in Makindye.',
  },
  {
    id: 'MAN-2026-000004',
    fullName: 'Kato Emmanuel',
    preferredName: 'Emma',
    gender: 'Male',
    phone: '+256 772 345678',
    email: 'emmanuel.kato@manifest.org',
    dateOfBirth: '2001-08-30',
    studentInfo: {
      isStudent: true,
      registrationNumber: '2021-08-06789',
      course: 'BSc Civil Engineering',
      faculty: 'School of Engineering & Applied Sciences',
      yearOfStudy: 4,
      campus: 'KIU - Main Campus (Kansanga)',
      expectedGraduationYear: 2026,
    },
    status: 'Active',
    isFirstTimer: false,
    dateOfFirstAttendance: '2022-09-10',
    registrationDate: '2022-09-12',
    howFoundManifest: 'Friend/Member',
    homeId: 'home-sinai',
    departmentIds: ['dept-coordination'],
    notes: 'Home Sinai shepherd along Ggaba Road.',
  },
  {
    id: 'MAN-2026-000005',
    fullName: 'Ssemwogerere David',
    preferredName: 'Dave',
    gender: 'Male',
    phone: '+256 784 551234',
    email: 'dave.ssemwo@gmail.com',
    dateOfBirth: '2002-06-18',
    studentInfo: {
      isStudent: true,
      registrationNumber: '2022-01-03310',
      course: 'Bachelor of Pharmacy (BPharm)',
      faculty: 'School of Pharmacy',
      yearOfStudy: 3,
      campus: 'KIU - School of Pharmacy (Kansanga)',
      expectedGraduationYear: 2027,
    },
    status: 'Active',
    isFirstTimer: false,
    dateOfFirstAttendance: '2023-02-14',
    registrationDate: '2023-02-15',
    howFoundManifest: 'Flyer/Poster',
    homeId: 'home-bethel',
    departmentIds: ['dept-prayer'],
  },
  {
    id: 'MAN-2026-000006',
    fullName: 'Okello Paul',
    preferredName: 'Paul',
    gender: 'Male',
    phone: '+256 756 778899',
    email: 'paul.okello@gmail.com',
    dateOfBirth: '2000-12-05',
    studentInfo: {
      isStudent: false,
      campus: 'KIU Graduate / Kansanga Professional',
      course: 'BSc Telecommunications & Networks',
      expectedGraduationYear: 2024,
    },
    status: 'Active',
    isFirstTimer: false,
    dateOfFirstAttendance: '2021-11-20',
    registrationDate: '2021-11-25',
    howFoundManifest: 'Campus Outreach',
    homeId: 'home-shiloh',
    departmentIds: ['dept-outreach'],
    notes: 'Missions and evangelism director in Makindye Division.',
  },
  {
    id: 'MAN-2026-000007',
    fullName: 'Atuhaire Brenda',
    preferredName: 'Brenda',
    gender: 'Female',
    phone: '+256 753 112233',
    email: 'brenda.atuhaire@yahoo.com',
    dateOfBirth: '2003-09-14',
    studentInfo: {
      isStudent: true,
      registrationNumber: '2023-08-01908',
      course: 'BA Public Administration',
      faculty: 'School of Humanities & Social Sciences',
      yearOfStudy: 2,
      campus: 'KIU - Main Campus (Kansanga)',
      expectedGraduationYear: 2027,
    },
    status: 'Active',
    isFirstTimer: false,
    dateOfFirstAttendance: '2024-03-05',
    registrationDate: '2024-03-07',
    howFoundManifest: 'Friend/Member',
    homeId: 'home-ebenezer',
    departmentIds: ['dept-protocol'],
  },
  {
    id: 'MAN-2026-000008',
    fullName: 'Nakato Grace',
    preferredName: 'Grace',
    gender: 'Female',
    phone: '+256 779 114477',
    email: 'grace.nakato@gmail.com',
    studentInfo: {
      isStudent: true,
      registrationNumber: '2022-01-06055',
      course: 'BSc Economics & Statistics',
      faculty: 'School of Business & Management',
      yearOfStudy: 3,
      campus: 'KIU - Main Campus (Kansanga)',
      expectedGraduationYear: 2026,
    },
    status: 'Active',
    isFirstTimer: false,
    dateOfFirstAttendance: '2023-04-12',
    registrationDate: '2023-04-15',
    howFoundManifest: 'Social Media',
    homeId: 'home-sinai',
    departmentIds: ['dept-protocol'],
  },
  {
    id: 'MAN-2026-000009',
    fullName: 'Kembabazi Sandra',
    preferredName: 'Sandra',
    gender: 'Female',
    phone: '+256 781 445566',
    email: 'sandra.kembabazi@manifest.org',
    studentInfo: {
      isStudent: true,
      registrationNumber: '2021-08-05533',
      course: 'Bachelor of International Relations',
      faculty: 'School of Humanities & Social Sciences',
      yearOfStudy: 4,
      campus: 'KIU - Main Campus (Kansanga)',
      expectedGraduationYear: 2026,
    },
    status: 'Active',
    isFirstTimer: false,
    dateOfFirstAttendance: '2022-10-04',
    registrationDate: '2022-10-08',
    howFoundManifest: 'Friend/Member',
    homeId: 'home-moriah',
    departmentIds: ['dept-protocol'],
    notes: 'Head Usher and Protocol Coordinator.',
  },
  {
    id: 'MAN-2026-000010',
    fullName: 'Ahebwa Faith',
    preferredName: 'Faith',
    gender: 'Female',
    phone: '+256 705 993311',
    email: 'faith.ahebwa@gmail.com',
    studentInfo: {
      isStudent: true,
      registrationNumber: '2023-01-07744',
      course: 'BSc Information Technology',
      faculty: 'School of Computing & IT',
      yearOfStudy: 2,
      campus: 'KIU - Main Campus (Kansanga)',
      expectedGraduationYear: 2027,
    },
    status: 'Active',
    isFirstTimer: false,
    dateOfFirstAttendance: '2024-02-18',
    registrationDate: '2024-02-20',
    howFoundManifest: 'Campus Outreach',
    homeId: 'home-zion',
    departmentIds: ['dept-media'],
  },
  // FIRST TIMERS
  {
    id: 'MAN-2026-000011',
    fullName: 'Turyamureeba Kevin',
    preferredName: 'Kevin',
    gender: 'Male',
    phone: '+256 789 220033',
    email: 'kevin.turya@gmail.com',
    dateOfBirth: '2004-05-19',
    studentInfo: {
      isStudent: true,
      registrationNumber: '2024-08-01209',
      course: 'BSc Electrical & Electronics Engineering',
      faculty: 'School of Engineering & Applied Sciences',
      yearOfStudy: 1,
      campus: 'KIU - Main Campus (Kansanga)',
      expectedGraduationYear: 2028,
    },
    status: 'First Timer',
    isFirstTimer: true,
    dateOfFirstAttendance: '2026-08-20',
    registrationDate: '2026-08-20',
    howFoundManifest: 'Campus Outreach',
    invitedBy: 'Okello Paul',
    homeId: 'home-sinai',
    departmentIds: [],
    notes: 'First-year KIU fresher residing at Dream World Hostels, Kansanga. Interested in media team.',
  },
  {
    id: 'MAN-2026-000012',
    fullName: 'Nalubega Patricia',
    preferredName: 'Patty',
    gender: 'Female',
    phone: '+256 706 443322',
    email: 'patricia.nalubega@yahoo.com',
    dateOfBirth: '2004-09-02',
    studentInfo: {
      isStudent: true,
      registrationNumber: '2024-08-08831',
      course: 'Bachelor of Mass Communication',
      faculty: 'School of Humanities & Social Sciences',
      yearOfStudy: 1,
      campus: 'KIU - Main Campus (Kansanga)',
      expectedGraduationYear: 2028,
    },
    status: 'First Timer',
    isFirstTimer: true,
    dateOfFirstAttendance: '2026-08-20',
    registrationDate: '2026-08-20',
    howFoundManifest: 'Friend/Member',
    invitedBy: 'Kembabazi Sandra',
    homeId: 'home-zion',
    departmentIds: [],
    notes: 'KIU Kansanga student residing in Kalungi area. Wants to serve in Media & Tech.',
  },
  {
    id: 'MAN-2026-000013',
    fullName: 'Mwesigwa Derick',
    preferredName: 'Derick',
    gender: 'Male',
    phone: '+256 773 881100',
    email: 'derick.mwesigwa@gmail.com',
    studentInfo: {
      isStudent: true,
      registrationNumber: '2023-05-04412',
      course: 'Bachelor of Business Computing',
      faculty: 'School of Business & Management',
      yearOfStudy: 2,
      campus: 'KIU - Main Campus (Kansanga)',
      expectedGraduationYear: 2027,
    },
    status: 'Returning Visitor',
    isFirstTimer: false,
    dateOfFirstAttendance: '2026-08-13',
    registrationDate: '2026-08-13',
    howFoundManifest: 'Social Media',
    homeId: 'home-moriah',
    departmentIds: [],
    notes: 'Resident of Lukuli Nanganda, Makindye. Attended second consecutive fellowship.',
  },
  {
    id: 'MAN-2026-000014',
    fullName: 'Akello Mercy',
    preferredName: 'Mercy',
    gender: 'Female',
    phone: '+256 704 332211',
    email: 'mercy.akello@manifest.org',
    studentInfo: {
      isStudent: true,
      registrationNumber: '2022-08-09912',
      course: 'Bachelor of Education (Arts)',
      faculty: 'School of Education',
      yearOfStudy: 3,
      campus: 'KIU - Main Campus (Kansanga)',
      expectedGraduationYear: 2026,
    },
    status: 'Active',
    isFirstTimer: false,
    dateOfFirstAttendance: '2023-01-20',
    registrationDate: '2023-01-22',
    howFoundManifest: 'Friend/Member',
    homeId: 'home-ebenezer',
    departmentIds: ['dept-coordination'],
    notes: 'Lead First-Timer Follow-Up Coordinator living near Ggaba.',
  },
  {
    id: 'MAN-2026-000015',
    fullName: 'Namubiru Joy',
    preferredName: 'Joy',
    gender: 'Female',
    phone: '+256 702 449911',
    email: 'joy.namubiru@gmail.com',
    studentInfo: {
      isStudent: true,
      registrationNumber: '2021-08-07711',
      course: 'Bachelor of Procurement & Logistics',
      faculty: 'School of Business & Management',
      yearOfStudy: 4,
      campus: 'KIU - Main Campus (Kansanga)',
      expectedGraduationYear: 2026,
    },
    status: 'Active',
    isFirstTimer: false,
    dateOfFirstAttendance: '2022-08-25',
    registrationDate: '2022-08-30',
    howFoundManifest: 'Friend/Member',
    homeId: 'home-moriah',
    departmentIds: [],
    notes: 'Home Moriah Shepherd in Makindye / Luwafu area.',
  },
  {
    id: 'MAN-2026-000016',
    fullName: 'Mutua Daniel',
    preferredName: 'Dan',
    gender: 'Male',
    phone: '+256 788 990011',
    email: 'daniel.mutua@manifestfellowship.org',
    studentInfo: {
      isStudent: false,
      campus: 'Makindye Professional / Resident',
      course: 'Certified Public Accountant (CPA-U)',
      expectedGraduationYear: 2023,
    },
    status: 'Active',
    isFirstTimer: false,
    dateOfFirstAttendance: '2021-08-10',
    registrationDate: '2021-08-12',
    howFoundManifest: 'Friend/Member',
    homeId: 'home-sinai',
    departmentIds: [],
    notes: 'Treasurer and accountant residing in Nsambya.',
  },
];

export const INITIAL_EVENTS: FellowshipEvent[] = [
  {
    id: 'evt-2026-01',
    name: 'Thursday Weekly Fellowship — "Walking in Light"',
    description: 'Our regular weekly worship, word, and corporate prayer gathering at KIU Kansanga.',
    eventType: 'Weekly Fellowship',
    date: '2026-08-20',
    startTime: '17:30',
    endTime: '20:00',
    location: 'KIU Main Campus Auditorium / Live Stream',
    requiresAttendance: true,
    status: 'Completed',
    budgetAllocated: 350000,
    expectedAttendance: 120,
    actualAttendanceCount: 108,
  },
  {
    id: 'evt-2026-02',
    name: 'Thursday Weekly Fellowship — "Rooted and Grounded"',
    description: 'Upcoming weekly gathering for KIU scholars and Makindye community.',
    eventType: 'Weekly Fellowship',
    date: '2026-08-27',
    startTime: '17:30',
    endTime: '20:00',
    location: 'KIU Main Campus Auditorium',
    requiresAttendance: true,
    status: 'Upcoming',
    budgetAllocated: 400000,
    expectedAttendance: 140,
  },
  {
    id: 'evt-2026-03',
    name: 'Manifest KIU Kansanga Freshers Campus Outreach',
    description: 'Welcoming first-year students across KIU faculties, hostels, and Kansanga residences.',
    eventType: 'Outreach',
    date: '2026-09-05',
    startTime: '09:00',
    endTime: '16:00',
    location: 'KIU Kansanga Campus & Hostels Quadrant',
    requiresAttendance: true,
    status: 'Upcoming',
    budgetAllocated: 800000,
    expectedAttendance: 250,
  },
  {
    id: 'evt-2026-04',
    name: 'Manifest Annual Worship & Word Conference 2026',
    description: 'Flagship university conference gathering students and fellowship alumni across Makindye Division.',
    eventType: 'Conference',
    date: '2026-10-16',
    startTime: '16:00',
    endTime: '21:00',
    location: 'Makindye Fellowship Pavilion & KIU Central Hall',
    requiresAttendance: true,
    status: 'Upcoming',
    budgetAllocated: 15500000,
    expectedAttendance: 600,
  },
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  {
    id: 'att-2026-001',
    memberId: 'MAN-2026-000001',
    memberName: 'Kigozi Joshua',
    memberPhone: '+256 703 118844',
    eventId: 'evt-2026-01',
    eventName: 'Thursday Weekly Fellowship — "Walking in Light"',
    date: '2026-08-20',
    time: '17:15',
    status: 'Present',
    recordedBy: 'Automatic QR Scanner',
    checkInMethod: 'QR Code',
  },
  {
    id: 'att-2026-002',
    memberId: 'MAN-2026-000002',
    memberName: 'Mugisha Brian',
    memberPhone: '+256 701 892341',
    eventId: 'evt-2026-01',
    eventName: 'Thursday Weekly Fellowship — "Walking in Light"',
    date: '2026-08-20',
    time: '17:22',
    status: 'Present',
    recordedBy: 'Automatic QR Scanner',
    checkInMethod: 'QR Code',
  },
  {
    id: 'att-2026-003',
    memberId: 'MAN-2026-000003',
    memberName: 'Nabatanzi Rachel',
    memberPhone: '+256 774 991122',
    eventId: 'evt-2026-01',
    eventName: 'Thursday Weekly Fellowship — "Walking in Light"',
    date: '2026-08-20',
    time: '17:28',
    status: 'Present',
    recordedBy: 'Officer Kembabazi',
    checkInMethod: 'Phone Lookup',
  },
  {
    id: 'att-2026-004',
    memberId: 'MAN-2026-000011',
    memberName: 'Turyamureeba Kevin',
    memberPhone: '+256 789 220033',
    eventId: 'evt-2026-01',
    eventName: 'Thursday Weekly Fellowship — "Walking in Light"',
    date: '2026-08-20',
    time: '17:40',
    status: 'Present',
    recordedBy: 'First-Timer Welcome Desk',
    notes: 'First visit! Given welcome pack and registered.',
    checkInMethod: 'Manual Roster',
  },
  {
    id: 'att-2026-005',
    memberId: 'MAN-2026-000012',
    memberName: 'Nalubega Patricia',
    memberPhone: '+256 706 443322',
    eventId: 'evt-2026-01',
    eventName: 'Thursday Weekly Fellowship — "Walking in Light"',
    date: '2026-08-20',
    time: '17:45',
    status: 'Present',
    recordedBy: 'First-Timer Welcome Desk',
    notes: 'First visit! Accompanied by Sandra.',
    checkInMethod: 'Manual Roster',
  },
];

export const INITIAL_FOLLOW_UPS: FollowUpRecord[] = [
  {
    id: 'fol-2026-001',
    memberId: 'MAN-2026-000011',
    memberName: 'Turyamureeba Kevin',
    phone: '+256 789 220033',
    dateOfVisit: '2026-08-20',
    invitedBy: 'Okello Paul',
    coordinatorId: 'MAN-2026-000014',
    coordinatorName: 'Akello Mercy',
    status: 'Contacted',
    notes: 'KIU Kansanga engineering fresher residing in Dream World Hostels. Warm spirit.',
    nextFollowUpDate: '2026-08-25',
    assignedHomeId: 'home-sinai',
    interactions: [
      {
        id: 'int-001',
        date: '2026-08-21',
        coordinatorId: 'MAN-2026-000014',
        coordinatorName: 'Akello Mercy',
        action: 'Phone Call',
        result: 'Called to welcome him. He expressed deep appreciation for the message and confirmed he will join Home Sinai cell meeting this Wednesday in Kansanga.',
        nextFollowUpDate: '2026-08-25',
      },
    ],
  },
  {
    id: 'fol-2026-002',
    memberId: 'MAN-2026-000012',
    memberName: 'Nalubega Patricia',
    phone: '+256 706 443322',
    dateOfVisit: '2026-08-20',
    invitedBy: 'Kembabazi Sandra',
    coordinatorId: 'MAN-2026-000008',
    coordinatorName: 'Nakato Grace',
    status: 'Assigned',
    notes: 'KIU Mass Comm student residing in Kansanga Kalungi area. Wants to serve in Media.',
    nextFollowUpDate: '2026-08-24',
    assignedHomeId: 'home-zion',
    interactions: [
      {
        id: 'int-002',
        date: '2026-08-21',
        coordinatorId: 'MAN-2026-000008',
        coordinatorName: 'Nakato Grace',
        action: 'WhatsApp / SMS',
        result: 'Sent warm welcome greeting text with info on Home Zion meeting time at Prestige Hostel.',
        nextFollowUpDate: '2026-08-24',
      },
    ],
  },
  {
    id: 'fol-2026-003',
    memberId: 'MAN-2026-000013',
    memberName: 'Mwesigwa Derick',
    phone: '+256 773 881100',
    dateOfVisit: '2026-08-13',
    coordinatorId: 'MAN-2026-000015',
    coordinatorName: 'Namubiru Joy',
    status: 'Joined',
    notes: 'Joined Home Moriah in Makindye / Lukuli. Regularly attending Thursday fellowship at KIU.',
    assignedHomeId: 'home-moriah',
    interactions: [
      {
        id: 'int-003',
        date: '2026-08-14',
        coordinatorId: 'MAN-2026-000015',
        coordinatorName: 'Namubiru Joy',
        action: 'Phone Call',
        result: 'Discussed Home Moriah weekly schedule and answered questions about discipleship classes in Makindye.',
      },
      {
        id: 'int-004',
        date: '2026-08-17',
        coordinatorId: 'MAN-2026-000015',
        coordinatorName: 'Namubiru Joy',
        action: 'In-Person Conversation',
        result: 'Met at KIU campus library gardens. Derick joined the Home fellowship cell meeting.',
      },
    ],
  },
];

export const INITIAL_INCOME: IncomeRecord[] = [
  {
    id: 'TXN-INC-2026-001',
    date: '2026-08-20',
    amount: 1450000,
    category: 'Offerings',
    description: 'Weekly Fellowship Offering (Cash & Mobile Money collections)',
    receivedBy: 'Mutua Daniel (Finance)',
    paymentMethod: 'Cash',
    referenceNumber: 'OFF-WK-34',
    eventId: 'evt-2026-01',
    status: 'Reconciled',
  },
  {
    id: 'TXN-INC-2026-002',
    date: '2026-08-18',
    amount: 3000000,
    category: 'Project Funding',
    description: 'Alumni & Partner contribution towards Sound Equipment Upgrade',
    receivedBy: 'Mutua Daniel (Finance)',
    paymentMethod: 'Bank Transfer',
    referenceNumber: 'STN-TXN-99824',
    projectId: 'proj-2026-02',
    status: 'Reconciled',
  },
  {
    id: 'TXN-INC-2026-003',
    date: '2026-08-15',
    amount: 850000,
    category: 'Donations',
    description: 'Special Monthly Patron Donation for KIU Student Welfare Fund',
    receivedBy: 'Mutua Daniel (Finance)',
    paymentMethod: 'MTN Mobile Money',
    referenceNumber: 'MM-884210-UG',
    status: 'Reconciled',
  },
];

export const INITIAL_EXPENSES: ExpenseRecord[] = [
  {
    id: 'TXN-EXP-2026-001',
    date: '2026-08-20',
    amount: 350000,
    category: 'Venue & Logistics',
    description: 'Auditorium electricity token and cleaning crew facilitation',
    requestedBy: 'Mutua Daniel (Finance)',
    approvedBy: 'Mutua Daniel (Finance)',
    paidBy: 'Campus Facilities Office',
    paymentMethod: 'Airtel Money',
    status: 'Approved',
  },
  {
    id: 'TXN-EXP-2026-002',
    date: '2026-08-19',
    amount: 280000,
    category: 'Outreach & Missions',
    description: 'Printed freshers outreach welcome tracts & Kansanga banners',
    requestedBy: 'Okello Paul (Outreach)',
    approvedBy: 'Mutua Daniel (Finance)',
    paidBy: 'Nasser Road Printers Ltd',
    paymentMethod: 'Cash',
    status: 'Approved',
  },
];

export const INITIAL_BUDGETS: Budget[] = [
  {
    id: 'bdg-2026-01',
    title: 'Manifest Annual Worship & Word Conference 2026',
    type: 'Conference' as any,
    targetId: 'evt-2026-04',
    totalAllocated: 15500000,
    totalSpent: 4200000,
    startDate: '2026-07-01',
    endDate: '2026-10-31',
    status: 'Active',
    createdBy: 'Mutua Daniel (Finance)',
    items: [
      { id: 'bitem-1', category: 'Venue & Logistics', name: 'Main Auditorium & Tents Rental', allocatedAmount: 5000000, spentAmount: 2000000, notes: '50% advance deposit paid' },
      { id: 'bitem-2', category: 'Equipment & Sound', name: 'Line Array Sound & LED Screen', allocatedAmount: 4000000, spentAmount: 1500000 },
      { id: 'bitem-3', category: 'Media & Tech', name: 'Multi-cam Live Stream & Production', allocatedAmount: 2000000, spentAmount: 500000 },
      { id: 'bitem-4', category: 'Printing & Publicity', name: 'Banners, Badges, Program Booklets', allocatedAmount: 1500000, spentAmount: 200000 },
      { id: 'bitem-5', category: 'Refreshments', name: 'Delegate Refreshments & Water', allocatedAmount: 1800000, spentAmount: 0 },
      { id: 'bitem-6', category: 'Honorarium', name: 'Guest Ministers Accommodation & Transport', allocatedAmount: 1200000, spentAmount: 0 },
    ],
  },
  {
    id: 'bdg-2026-02',
    title: 'Freshers Outreach & KIU Kansanga Campus Missions 2026',
    type: 'Project',
    targetId: 'proj-2026-03',
    totalAllocated: 2400000,
    totalSpent: 980000,
    startDate: '2026-08-01',
    endDate: '2026-09-30',
    status: 'Active',
    createdBy: 'Okello Paul (Outreach)',
    items: [
      { id: 'bitem-21', category: 'Transport', name: 'Kansanga Hostels Shuttle & Van Fuel', allocatedAmount: 600000, spentAmount: 300000 },
      { id: 'bitem-22', category: 'Printing & Publicity', name: 'Freshers Survival Guides & Tracts', allocatedAmount: 800000, spentAmount: 450000 },
      { id: 'bitem-23', category: 'Refreshments', name: 'Outreach Team Water & Snacks', allocatedAmount: 500000, spentAmount: 230000 },
      { id: 'bitem-24', category: 'Welfare & Hospitality', name: 'Freshers Welcome Gift Packs', allocatedAmount: 500000, spentAmount: 0 },
    ],
  },
  {
    id: 'bdg-2026-03',
    title: 'Q3 Media & Production Ministry Operations',
    type: 'Department',
    targetId: 'dept-media',
    totalAllocated: 3200000,
    totalSpent: 1650000,
    startDate: '2026-07-01',
    endDate: '2026-09-30',
    status: 'Active',
    createdBy: 'Kigozi Joshua (Media)',
    items: [
      { id: 'bitem-31', category: 'Media & Tech', name: 'Internet Data Bundles & Cloud Storage', allocatedAmount: 900000, spentAmount: 600000 },
      { id: 'bitem-32', category: 'Equipment & Sound', name: 'Cables, Batteries & Audio Accessories', allocatedAmount: 1300000, spentAmount: 750000 },
      { id: 'bitem-33', category: 'Transport', name: 'Media Gear Transport & Logistics', allocatedAmount: 1000000, spentAmount: 300000 },
    ],
  },
];

export const INITIAL_PROJECTS: FinancialProject[] = [
  {
    id: 'proj-2026-01',
    title: 'Manifest Annual Worship & Word Conference 2026',
    description: 'Flagship campus conference gathering over 600 KIU scholars, Makindye residents, and alumni.',
    coordinatorName: 'Kato Emmanuel & Mutua Daniel',
    budgetTarget: 15500000,
    totalIncome: 7500000,
    totalExpenses: 4200000,
    status: 'Active',
    startDate: '2026-07-01',
    endDate: '2026-10-31',
  },
  {
    id: 'proj-2026-02',
    title: 'Sound & Multi-Media Modernization Project',
    description: 'Acquiring digital mixer, HD cameras, and stage lighting for KIU fellowship auditorium live stream.',
    coordinatorName: 'Kigozi Joshua',
    budgetTarget: 8000000,
    totalIncome: 5500000,
    totalExpenses: 3400000,
    status: 'Active',
    startDate: '2026-06-01',
    endDate: '2026-12-31',
  },
  {
    id: 'proj-2026-03',
    title: 'KIU Freshers Evangelism & Welcome Mission',
    description: 'Outreach initiative to welcome 2026 freshers across KIU Kansanga hostels and Makindye residences.',
    coordinatorName: 'Okello Paul',
    budgetTarget: 2400000,
    totalIncome: 1800000,
    totalExpenses: 980000,
    status: 'Active',
    startDate: '2026-08-01',
    endDate: '2026-09-30',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud-001',
    timestamp: '2026-08-20T20:15:00Z',
    userName: 'Kigozi Joshua',
    userRole: 'Super Admin',
    module: 'Attendance',
    action: 'Batch Attendance Reconciled',
    targetEntityId: 'evt-2026-01',
    details: 'Checked in 108 attendees for Thursday Weekly Fellowship at KIU Kansanga via QR and Phone search.',
    result: 'Success',
  },
  {
    id: 'aud-002',
    timestamp: '2026-08-20T17:40:00Z',
    userName: 'Akello Mercy',
    userRole: 'Coordinator',
    module: 'Members',
    action: 'First Timer Registered & Onboarded',
    targetEntityId: 'MAN-2026-000011',
    details: 'Automated workflow: Created member MAN-2026-000011 (Turyamureeba Kevin) and opened follow-up case fol-2026-001.',
    result: 'Success',
  },
  {
    id: 'aud-003',
    timestamp: '2026-08-20T21:00:00Z',
    userName: 'Mutua Daniel',
    userRole: 'Finance Admin',
    module: 'Finance',
    action: 'Income Recorded',
    targetEntityId: 'TXN-INC-2026-001',
    details: 'Recorded UGX 1,450,000 weekly fellowship offering collection at KIU Kansanga.',
    result: 'Success',
  },
  {
    id: 'aud-004',
    timestamp: '2026-08-21T10:30:00Z',
    userName: 'Mutua Daniel',
    userRole: 'Super Admin',
    module: 'Finance',
    action: 'Expense Approved & Disbursed',
    targetEntityId: 'TXN-EXP-2026-001',
    details: 'Approved and disbursed UGX 350,000 for auditorium facilities facilitation.',
    result: 'Success',
  },
  {
    id: 'aud-005',
    timestamp: '2026-08-21T15:00:00Z',
    userName: 'Akello Mercy',
    userRole: 'Coordinator',
    module: 'Follow-Up',
    action: 'Follow-Up Interaction Logged',
    targetEntityId: 'fol-2026-001',
    details: 'Phone call logged for Kevin Turyamureeba. Status changed to Contacted.',
    result: 'Success',
  },
];

export const INITIAL_MESSAGES: CommunicationMessage[] = [
  {
    id: 'msg-001',
    timestamp: '2026-08-20T10:00:00Z',
    senderName: 'Fellowship Secretariat',
    channel: 'SMS',
    title: 'Weekly Fellowship Reminder',
    body: 'Grace and peace! Join us tonight at 5:30 PM for our Weekly Fellowship: "Walking in Light" at KIU Main Campus Auditorium. Come ready for deep worship and fellowship!',
    recipientGroup: 'All Members',
    recipientCount: 16,
    status: 'Sent',
  },
  {
    id: 'msg-002',
    timestamp: '2026-08-21T09:00:00Z',
    senderName: 'Akello Mercy (Coordination)',
    channel: 'SMS',
    title: 'First-Timer Welcome Message',
    body: 'Dear {name}, thank you for joining Manifest Fellowship at KIU Kansanga this week! You are family here. Look forward to connecting with you and welcoming you to our Home fellowship.',
    recipientGroup: 'First Timers',
    recipientCount: 2,
    status: 'Sent',
  },
  {
    id: 'msg-003',
    timestamp: '2026-08-22T14:30:00Z',
    senderName: 'Manifest Leadership',
    channel: 'Announcement',
    title: 'Manifest Annual Conference 2026 Registration Opened',
    body: 'Registration and volunteer sign-ups for Manifest Annual Worship & Word Conference 2026 are officially open across KIU Kansanga and Makindye cell homes. Reach out to your Home leader to get involved!',
    recipientGroup: 'All Members',
    recipientCount: 16,
    status: 'Sent',
  },
];
